// grizzlars_module.cpp — nanobind entry point. The class/method bindings
// themselves are auto-generated by litgen from grizzlars_shim.h (see
// tools/generate_bindings.py); this file only wires up module-level extras
// (thread-pool control) that aren't part of the GrizzlarFrame class itself.
#include <nanobind/nanobind.h>
#include <nanobind/stl/map.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>

#include <DataFrame/Utils/Threads/ThreadGranularity.h>

#include "grizzlars_shim.h"

namespace nb = nanobind;

NB_MODULE(_grizzlars, m)
{
    m.def("set_thread_level", [](unsigned int n) { hmdf::ThreadGranularity::set_thread_level(n); });
    m.def("set_optimum_thread_level", []() { hmdf::ThreadGranularity::set_optimum_thread_level(); });
    m.def("get_thread_level", []() { return static_cast<unsigned int>(hmdf::ThreadGranularity::get_thread_level()); });

#include "grizzlars_glue.inc"
}
